Fix build on ARM
When building a package for Mer, the build fails with the following
error:

/opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_algo.h:2266:34:
error: invalid initialization of reference of type
'QSharedPointer<KScreen::Output>&' from expression of type 'const
QSharedPointer<KScreen::Output>'

Using qSort instead of std::sort fixes this.